# Service Kubernetes per esporre il backend HackHub all'interno del cluster
apiVersion: v1
kind: Service
metadata:
  name: backend-quarkus-service
spec:
  selector:
    app: hackhub-backend-quarkus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080